### ISSUE TITLE
U forgot to add the code lmao

### ISSUE THREAD

**Issue by therealtear** [Aiueokashi/discord-bot-token-detector#1]
( ͡° ͜ʖ ͡°)

**Comment by Aiueokashi** [comment]
OOf sorry 
I’ll add code someday...

**Comment by therealtear** [comment]
> OOf sorry
> I’ll add code someday...

Lol it’s ok

**Comment by BlueTree242** [comment]
SCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM
